"""
dashboard/reporting.py
Generates downloadable bias reports in PDF and Markdown formats.
"""

import io
import json
from datetime import datetime

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


# ── Markdown Report ────────────────────────────────────────────────────────────

def generate_markdown_report(
    metrics: dict,
    ai_results: dict,
    target_col: str,
    sensitive_col: str,
    filename: str = "dataset.csv",
) -> str:
    """
    Generate a complete Markdown bias audit report.

    Returns
    -------
    str : Markdown-formatted report string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bias_status = "⚠️ BIAS DETECTED" if metrics.get("bias_detected") else "✅ No Significant Bias"
    score = metrics.get("fairness_score", 0)
    grade = "🟢 Good" if score >= 80 else ("🟡 Moderate" if score >= 60 else "🔴 Poor")

    group_rates = metrics.get("group_positive_rates", {})
    group_table_rows = "\n".join(
        f"| {g} | {r:.4f} | {r:.1%} |"
        for g, r in group_rates.items()
    )

    explanation  = ai_results.get("explanation", "_Not generated._")
    recommendations = ai_results.get("recommendations", "_Not generated._")
    report_summary  = ai_results.get("report_summary", "_Not generated._")

    report = f"""# FairAI – Bias Detection Report
**Generated:** {now}
**Dataset:** {filename}
**Target Variable:** `{target_col}`
**Protected Attribute:** `{sensitive_col}`

---

## Executive Summary
{report_summary}

---

## Bias Status

| Metric | Value |
|--------|-------|
| **Overall Fairness Score** | **{score}/100** {grade} |
| **Bias Status** | {bias_status} |
| Demographic Parity Difference | `{metrics.get('demographic_parity_difference', 0):.4f}` |
| Equalized Odds Difference | `{metrics.get('equalized_odds_difference', 0):.4f}` |
| Disparate Impact Ratio | `{metrics.get('disparate_impact', 1):.4f}` |
| Total Samples Analyzed | `{metrics.get('n_samples', 'N/A')}` |
| Number of Groups | `{metrics.get('n_groups', 'N/A')}` |

---

## Group Positive Rates

| Group | Rate (Float) | Rate (%) |
|-------|-------------|---------|
{group_table_rows}

---

## AI Explanation

{explanation}

---

## Mitigation Recommendations

{recommendations}

---

## Metric Interpretations

| Metric | Ideal Value | Current | Interpretation |
|--------|------------|---------|---------------|
| Demographic Parity Difference | 0.0 | {metrics.get('demographic_parity_difference', 0):.4f} | Difference in positive rates. Values > 0.1 indicate bias. |
| Equalized Odds Difference | 0.0 | {metrics.get('equalized_odds_difference', 0):.4f} | Difference in TPR/FPR across groups. Values > 0.1 are concerning. |
| Disparate Impact | 1.0 | {metrics.get('disparate_impact', 1):.4f} | Ratio of positive rates. Values < 0.8 violate the 80% rule. |

---

## JSON Export

```json
{json.dumps(metrics, indent=2)}
```

---
*Report generated by [FairAI](https://github.com/buildwithanish) – Bias Detection and Fairness Analysis Platform*
"""
    return report


# ── PDF Report ────────────────────────────────────────────────────────────────

class _FairAIPDF(FPDF if FPDF_AVAILABLE else object):
    """Custom FPDF subclass with header/footer branding."""

    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_fill_color(30, 30, 50)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "  FairAI - Bias Detection Report", align="L", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by FairAI", align="C")


def generate_pdf_report(
    metrics: dict,
    ai_results: dict,
    target_col: str,
    sensitive_col: str,
    filename: str = "dataset.csv",
) -> bytes:
    """
    Generate a PDF bias audit report.

    Returns
    -------
    bytes : PDF file content as bytes (can be downloaded via Streamlit).
    """
    if not FPDF_AVAILABLE:
        raise ImportError("fpdf2 is not installed. Run: pip install fpdf2")

    now   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    score = metrics.get("fairness_score", 0)
    bias  = metrics.get("bias_detected", False)
    grade = "Good" if score >= 80 else ("Moderate" if score >= 60 else "Poor")

    pdf = _FairAIPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Meta info ─────────────────────────────────────────
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Generated: {now}   |   Dataset: {filename}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Target: {target_col}   |   Protected Attribute: {sensitive_col}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    def section_title(title: str):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(50, 50, 80)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(30, 30, 30)
        pdf.ln(3)

    def kv_row(key: str, value: str, highlight: bool = False):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(75, 7, key)
        pdf.set_font("Helvetica", size=10)
        if highlight:
            pdf.set_text_color(200, 50, 50) if bias else pdf.set_text_color(50, 160, 50)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(30, 30, 30)

    # ── Summary Section ────────────────────────────────────
    section_title("Fairness Summary")
    kv_row("Fairness Score:", f"{score}/100  ({grade})")
    kv_row("Bias Status:", "BIAS DETECTED" if bias else "No Significant Bias", highlight=True)
    kv_row("Demographic Parity Diff.:", f"{metrics.get('demographic_parity_difference', 0):.4f}")
    kv_row("Equalized Odds Diff.:", f"{metrics.get('equalized_odds_difference', 0):.4f}")
    kv_row("Disparate Impact:", f"{metrics.get('disparate_impact', 1):.4f}")
    kv_row("Total Samples:", str(metrics.get("n_samples", "N/A")))
    kv_row("Groups Found:", str(metrics.get("n_groups", "N/A")))
    pdf.ln(4)

    # ── Group Rates ────────────────────────────────────────
    section_title("Group Positive Rates")
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(80, 7, "Group")
    pdf.cell(40, 7, "Rate (Float)")
    pdf.cell(40, 7, "Rate (%)")
    pdf.ln()
    pdf.set_font("Helvetica", size=10)
    for g, r in metrics.get("group_positive_rates", {}).items():
        pdf.cell(80, 7, str(g))
        pdf.cell(40, 7, f"{r:.4f}")
        pdf.cell(40, 7, f"{r:.1%}")
        pdf.ln()
    pdf.ln(4)

    # ── AI Sections ────────────────────────────────────────
    def ai_section(title: str, content: str):
        section_title(title)
        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(30, 30, 30)
        # Strip markdown bold/italic for PDF
        import re
        clean = re.sub(r"\*+([^*]+)\*+", r"\1", content or "_Not generated._")
        clean = re.sub(r"#{1,6}\s*", "", clean)
        clean = clean.replace("–", "-").replace("—", "-").replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'").replace("•", "-")
        clean = clean.strip()
        pdf.multi_cell(0, 6, clean)
        pdf.ln(4)

    exec_summary = ai_results.get("report_summary") or "Not generated."
    ai_section("Executive Summary", exec_summary)

    explanation = ai_results.get("explanation") or "Not generated."
    ai_section("Bias Explanation", explanation)

    recommendations = ai_results.get("recommendations") or "Not generated."
    ai_section("Mitigation Recommendations", recommendations)

    return bytes(pdf.output())
